//STEP 2 DESIGN THE TYPES OF ACTION THE STATE MAY SUFFER

export const GET_SMURF ="GET_SMURF"
export const GET_SMURF_SUCCESS ="GET_SMURF_SUCCESS"
export const GET_SMURF_FAILURE="GET_SMURF_FAILURE"
export const POST_SMURF="POST_SMURF"
export const POST_SMURF_SUCCESS="POST_SMURF_SUCCESS"
export const POST_SMURF_FAILURE="POST_SMURF_FAILURE"


